#!/usr/bin/with-contenv sh

export DASPANEL_CONTAINER_TYPE="svc-panel"
printf $DASPANEL_CONTAINER_TYPE > /var/run/s6/container_environment/DASPANEL_CONTAINER_TYPE

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    exit 1
fi

case "$DASPANEL_WAIT_FOR_API" in
    YES|yes|Yes)
        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Waiting 60 seconds for API: $0" >&2
        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
        result=$?
        if [ ! $result -eq 0 ] ; then
            echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
            exit 1
        fi
        ;;
    *) 
        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Container not need to wait API become online: $0" >&2
        exit 1
        ;;
esac

echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Waiting 60 seconds for Mail Server: $0" >&2
/opt/daspanel/bin/wait-for -t 60 daspanel-mail-catcher:1025
result=$?
if [ ! $result -eq 0 ] ; then
    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Can not connect to Mail Server: daspanel-mail-catcher 1025" >&2
    exit 1
fi

# Get system configs from API server and set env variables
SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
result=$?
if [ ! $result -eq 0 ] ; then
    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Unable to get tenant configuration from API server: $0" >&2
    exit 1
fi
export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.hostname'`
export DASPANEL_SYS_ADMIN=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.admin'`
export DASPANEL_SYS_PASSWORD=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.password'`
export DASPANEL_SMTP_USER=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.smtp.user'`

# Send email with instance info
export DASPANEL_URL="https://api.$DASPANEL_SYS_HOSTNAME"
export DASPANEL_API_URL="https://api.$DASPANEL_SYS_HOSTNAME/1.0/sites/"
export DASPANEL_API_DOCS="https://api.$DASPANEL_SYS_HOSTNAME/1.0/sites/ui/"

ERR=1
MAX_TRIES=4
COUNT=0
while [  $COUNT -lt $MAX_TRIES ]; do
	{
	    echo "To: $DASPANEL_SYS_ADMIN"; 
	    echo "From: $DASPANEL_SMTP_USER"; 
	    echo "Subject: DASPANEL instance $DASPANEL_SYS_UUID is running"; 
	    echo "";
	    echo "Control Panel URL:";
	    echo "   https://admin.$DASPANEL_SYS_HOSTNAME";
	    echo "";
	    echo "Control Panel User:";
	    echo "   $DASPANEL_SYS_ADMIN";
	    echo "";
	    echo "Control Panel User Password:";
	    echo "   $DASPANEL_SYS_PASSWORD";
	    echo "";
	    echo "";
	    echo "X-Api-Key:";
	    echo "   $DASPANEL_SYS_UUID";
	    echo ""; 
	    echo "API Url:";
	    echo "   $DASPANEL_API_URL";
	    echo "";
	    echo "API Docs Url:";
	    echo "   $DASPANEL_API_DOCS";
	    echo ""; 
	    echo "";
	    if [ -f /opt/daspanel/data/$DASPANEL_SYS_UUID/containers/mysql.configured ]; then
	        echo "*** MYSQL CONFIG ***";
	        echo "$(cat /opt/daspanel/data/$DASPANEL_SYS_UUID/containers/mysql.configured)";
	    fi
	    echo ""; 
	    echo "";
	    if [ -f /opt/daspanel/data/$DASPANEL_SYS_UUID/containers/s3.configured ]; then
	        echo "*** S3 CONFIG ***";
	        echo "$(cat /opt/daspanel/data/$DASPANEL_SYS_UUID/containers/s3.configured)";
	    fi
	    echo "";
	    echo "";
	    echo "*** DASPANEL System Config ***";
        echo "$(echo $SYSCFG | /opt/daspanel/bin/jq .)";
	    echo ""; 
	    echo ""; 
	} | ssmtp $DASPANEL_SYS_ADMIN
    if [ $? -eq 0 ];then
		echo "daspanel-api: Sending setup info email to $DASPANEL_SYS_ADMIN"
        break
	else
		echo "Tentativa: $COUNT" 
		if [ $COUNT -eq $(( $MAX_TRIES - 1 )) ];then
			echo "End email sending attempts after $MAX_TRIES tries"
			break
		fi
        echo "Waiting 5 seconds"
        wait 5
    fi
    let COUNT=COUNT+1
done

